# Generated by Django 5.2.8 on 2026-05-14 09:32

from django.db import migrations
from decimal import Decimal
from django.utils import timezone
import datetime

def migrate_payment_logs(apps, schema_editor):
    PaymentLog = apps.get_model('finance', 'PaymentLog')
    FinancialAccount = apps.get_model('finance', 'FinancialAccount')
    FinanceCategory = apps.get_model('finance', 'FinanceCategory')
    FinancialTransaction = apps.get_model('finance', 'FinancialTransaction')

    if not PaymentLog.objects.exists():
        return

    # Create default accounts
    cash_account, _ = FinancialAccount.objects.get_or_create(
        name="Kas Utama (Migrasi)",
        defaults={'account_type': 'CASH', 'balance': Decimal('0')}
    )

    # Create default categories
    income_cat, _ = FinanceCategory.objects.get_or_create(
        name="Penerimaan Piutang", defaults={'category_type': 'INCOME'}
    )
    expense_cat, _ = FinanceCategory.objects.get_or_create(
        name="Pelunasan Hutang", defaults={'category_type': 'EXPENSE'}
    )

    for log in PaymentLog.objects.all():
        header = log.transaction
        # Determine IN/OUT based on transaction type (SALE -> IN, PURCHASE -> OUT)
        if header.trx_type == 'SALE':
            trx_type = 'IN'
            dest_acc = cash_account
            src_acc = None
            cat = income_cat
            # Update balance
            cash_account.balance += log.amount_paid
        else: # PURCHASE
            trx_type = 'OUT'
            src_acc = cash_account
            dest_acc = None
            cat = expense_cat
            # Update balance
            cash_account.balance -= log.amount_paid
            
        dt_val = timezone.now()
        if log.payment_date:
            dt_val = datetime.datetime.combine(log.payment_date, datetime.time.min).replace(tzinfo=datetime.timezone.utc)
            
        FinancialTransaction.objects.create(
            transaction_type=trx_type,
            source_account=src_acc,
            destination_account=dest_acc,
            category=cat,
            ref_invoice=header,
            amount=log.amount_paid,
            fee=Decimal('0'),
            date=dt_val,
            note=log.note or f"Migrasi dari PaymentLog ID {log.id}"
        )
        
    cash_account.save()

def reverse_migration(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_financecategory_financialaccount_and_more'),
    ]

    operations = [
        migrations.RunPython(migrate_payment_logs, reverse_migration),
    ]
