# Generated by Django 5.2.8 on 2026-05-11 05:17

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0003_product_brand_product_category_product_notes_and_more'),
        ('partner', '0001_initial'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_number', models.CharField(max_length=20, unique=True)),
                ('checkin_date', models.DateField(default=django.utils.timezone.localdate)),
                ('device_type', models.CharField(blank=True, default='', max_length=50)),
                ('device_brand', models.CharField(blank=True, default='', max_length=100)),
                ('device_model', models.CharField(blank=True, default='', max_length=100)),
                ('device_color', models.CharField(blank=True, default='', max_length=100)),
                ('device_name', models.CharField(max_length=200)),
                ('serial_number', models.CharField(blank=True, default='', max_length=100)),
                ('complaint', models.TextField()),
                ('initial_diagnosis', models.TextField(blank=True, default='')),
                ('completeness', models.TextField(blank=True, default='')),
                ('completeness_notes', models.CharField(blank=True, default='', max_length=255)),
                ('condition', models.TextField(blank=True, default='')),
                ('priority', models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=15)),
                ('technician_name', models.CharField(blank=True, default='', max_length=120)),
                ('estimated_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('estimated_completion', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('RECEIVED', 'Diterima'), ('DIAGNOSING', 'Pengecekan'), ('WAITING', 'Menunggu Part'), ('REPAIRING', 'Perbaikan'), ('READY', 'Siap Diambil'), ('DONE', 'Selesai'), ('PICKED', 'Diambil'), ('CANCELLED', 'Batal')], default='RECEIVED', max_length=15)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('warranty_void_informed', models.BooleanField(default=False)),
                ('customer_agreement', models.BooleanField(default=False)),
                ('labor_fee', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('labor_description', models.CharField(blank=True, default='', max_length=255)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('invoice_notes', models.TextField(blank=True, default='')),
                ('warranty_days', models.PositiveIntegerField(default=0)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner.contact')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_info', to='transaction.transactionheader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceTicketLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('log_type', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('repair_action', 'Repair Action'), ('part_used', 'Part Used'), ('waiting_note', 'Waiting Note'), ('customer_contact', 'Customer Contact'), ('qc_check', 'QC Check'), ('completed', 'Completed'), ('checkin', 'Check-in'), ('status', 'Status Change')], max_length=30)),
                ('technician_name', models.CharField(blank=True, default='', max_length=120)),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='service.serviceticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceTicketPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='service.serviceticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
