# Generated by Django 6.0.4 on 2026-05-12 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticketpart',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='serviceticketpart',
            name='product',
        ),
        migrations.RemoveField(
            model_name='serviceticketpart',
            name='ticket',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='labor_fee',
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='checkin_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='completeness',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='condition',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='device_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='device_type',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='estimated_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='priority',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('URGENT', 'Urgent'), ('EMERGENCY', 'Emergency')], default='NORMAL', max_length=10),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='status',
            field=models.CharField(choices=[('RECEIVED', 'Diterima'), ('DIAGNOSING', 'Pengecekan'), ('WAITING', 'Menunggu Part'), ('REPAIRING', 'Perbaikan'), ('DONE', 'Siap Diambil'), ('PICKED', 'Diambil'), ('CANCELLED', 'Batal')], default='RECEIVED', max_length=15),
        ),
        migrations.AlterField(
            model_name='serviceticket',
            name='technician_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.CreateModel(
            name='ServiceWorkLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, default='', max_length=150)),
                ('log_type', models.CharField(choices=[('diagnosis', 'Diagnosis'), ('repair_action', 'Repair Action'), ('part_used', 'Part Used'), ('waiting_note', 'Waiting Note'), ('customer_contact', 'Customer Contact'), ('qc_check', 'QC Check'), ('completed', 'Completed')], max_length=30)),
                ('technician_name', models.CharField(blank=True, default='', max_length=150)),
                ('note', models.TextField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worklogs', to='service.serviceticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ServiceTicketLog',
        ),
        migrations.DeleteModel(
            name='ServiceTicketPart',
        ),
    ]
