# Generated by Django 6.0.4 on 2026-05-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_remove_serviceticketpart_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceticket',
            name='device_model',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='estimated_completion',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='estimated_cost',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='initial_diagnosis',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='internal_notes',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='labor_description',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='technician_name',
        ),
        migrations.RemoveField(
            model_name='serviceticket',
            name='warranty_void_informed',
        ),
        migrations.DeleteModel(
            name='ServiceWorkLog',
        ),
    ]
