# Generated by Django 5.2.8 on 2026-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='branch',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
