# Generated by Django 5.2.8 on 2026-05-09 17:22

from django.db import migrations, models


def forwards_normalize_product_type(apps, schema_editor):
    Product = apps.get_model("inventory", "Product")
    Product.objects.filter(product_type="GOODS").update(product_type="PRODUCT")


def backwards_normalize_product_type(apps, schema_editor):
    # Keep backwards migration safe: do not reintroduce invalid values.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_branch_email_branch_manager_branch_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('PRODUCT', 'Produk Fisik'), (
                'SERVICE', 'Jasa/Layanan')], default='PRODUCT', max_length=10),
        ),
        migrations.RunPython(
            forwards_normalize_product_type,
            backwards_normalize_product_type,
        ),
    ]
