# Generated by Django 5.2.8 on 2026-06-20 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_product_brand_product_category_product_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='docs',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
