# Generated by Django 6.0.4 on 2026-04-28 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('partner', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invoice_number', models.CharField(max_length=50, unique=True)),
                ('trx_type', models.CharField(choices=[('SALE', 'Penjualan'), ('PURCHASE', 'Pembelian')], max_length=10)),
                ('payment_method', models.CharField(choices=[('CASH', 'Tunai'), ('CREDIT', 'Tempo/Hutang')], max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.branch')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='partner.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TransactionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField()),
                ('price_at_trx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cost_at_trx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product')),
                ('header', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='transaction.transactionheader')),
            ],
        ),
    ]
