# Generated by Django 6.0.4 on 2026-05-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_transactiondetail_related_service_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactiondetail',
            name='related_service_ticket',
        ),
    ]
