# Generated by Django 6.0.4 on 2026-06-25 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('global', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyprofile',
            name='maps_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
